// Products Data for Ai-oko Fabrics Store
const productsData = {
    // Ankara Products (6 yards per piece)
    ankara: [
        {
            id: 'ANK001',
            name: 'Hitarget Ankara Design 1',
            price: 15000,
            image: 'images/ankara-hitarget.jpg',
            category: 'ankara',
            subcategory: 'Hitarget',
            colors: ['red', 'blue', 'yellow'],
            colorTags: ['red', 'blue', 'yellow'],
            colorCombination: 'red & blue & yellow',
            description: 'Premium Hitarget Ankara fabric with vibrant colors and patterns.',
            size: '6 yards',
            sku: 'ANK-HTG-001',
            pattern: 'Geometric'
        },
        {
            id: 'ANK002',
            name: 'Hitarget Ankara Design 2',
            price: 15000,
            image: 'images/ankara-hitarget-2.jpg',
            category: 'ankara',
            subcategory: 'Hitarget',
            colors: ['green', 'blue'],
            colorTags: ['green', 'blue'],
            colorCombination: 'green & blue',
            description: 'Hitarget Ankara with green and blue geometric patterns.',
            size: '6 yards',
            sku: 'ANK-HTG-002',
            pattern: 'Geometric'
        },
        {
            id: 'ANK003',
            name: 'Hitarget Ankara Design 3',
            price: 15000,
            image: 'images/ankara-hitarget-3.jpg',
            category: 'ankara',
            subcategory: 'Hitarget',
            colors: ['red', 'black', 'white'],
            colorTags: ['red', 'black', 'white'],
            colorCombination: 'red & black & white',
            description: 'Hitarget Ankara with contrasting red, black, and white design.',
            size: '6 yards',
            sku: 'ANK-HTG-003',
            pattern: 'Abstract'
        },
        {
            id: 'ANK004',
            name: 'Hitarget Ankara Design 4',
            price: 15000,
            image: 'images/ankara-hitarget-4.jpg',
            category: 'ankara',
            subcategory: 'Hitarget',
            colors: ['purple', 'gold'],
            colorTags: ['purple', 'gold'],
            colorCombination: 'purple & gold',
            description: 'Elegant Hitarget Ankara with purple and gold royal patterns.',
            size: '6 yards',
            sku: 'ANK-HTG-004',
            pattern: 'Traditional'
        },
        {
            id: 'ANK005',
            name: 'Medium Chingavy Design 1',
            price: 15000,
            image: 'images/ankara-chingavy.jpg',
            category: 'ankara',
            subcategory: 'Medium Chingavy',
            colors: ['green', 'blue'],
            colorTags: ['green', 'blue'],
            colorCombination: 'green & blue',
            description: 'Medium quality Chingavy fabric with intricate patterns.',
            size: '6 yards',
            sku: 'ANK-MCH-005',
            pattern: 'Floral'
        },
        {
            id: 'ANK006',
            name: 'Medium Chingavy Design 2',
            price: 15000,
            image: 'images/ankara-chingavy-2.jpg',
            category: 'ankara',
            subcategory: 'Medium Chingavy',
            colors: ['red', 'yellow', 'black'],
            colorTags: ['red', 'yellow', 'black'],
            colorCombination: 'red & yellow & black',
            description: 'Vibrant Chingavy with traditional Nigerian patterns.',
            size: '6 yards',
            sku: 'ANK-MCH-006',
            pattern: 'Traditional'
        },
        {
            id: 'ANK007',
            name: 'Mali Ankara Design 1',
            price: 25000,
            image: 'images/ankara-mali.jpg',
            category: 'ankara',
            subcategory: 'Mali',
            colors: ['red', 'black'],
            colorTags: ['red', 'black'],
            colorCombination: 'red & black',
            description: 'High-quality Mali Ankara with premium wax prints.',
            size: '6 yards',
            sku: 'ANK-MAL-007',
            pattern: 'Abstract'
        },
        {
            id: 'ANK008',
            name: 'Mali Ankara Design 2',
            price: 25000,
            image: 'images/ankara-mali-2.jpg',
            category: 'ankara',
            subcategory: 'Mali',
            colors: ['blue', 'gold', 'white'],
            colorTags: ['blue', 'gold', 'white'],
            colorCombination: 'blue & gold & white',
            description: 'Premium Mali Ankara with blue and gold accents.',
            size: '6 yards',
            sku: 'ANK-MAL-008',
            pattern: 'Geometric'
        },
        {
            id: 'ANK009',
            name: 'Akwete Ankara Design 1',
            price: 17000,
            image: 'images/ankara-akwete.jpg',
            category: 'ankara',
            subcategory: 'Akwete',
            colors: ['brown', 'orange'],
            colorTags: ['brown', 'orange'],
            colorCombination: 'brown & orange',
            description: 'Traditional Akwete design Ankara fabric.',
            size: '6 yards',
            sku: 'ANK-AKW-009',
            pattern: 'Traditional'
        },
        {
            id: 'ANK010',
            name: 'Akwete Ankara Design 2',
            price: 17000,
            image: 'images/ankara-akwete-2.jpg',
            category: 'ankara',
            subcategory: 'Akwete',
            colors: ['green', 'yellow', 'brown'],
            colorTags: ['green', 'yellow', 'brown'],
            colorCombination: 'green & yellow & brown',
            description: 'Akwete Ankara with earthy tones and patterns.',
            size: '6 yards',
            sku: 'ANK-AKW-010',
            pattern: 'Ethnic'
        },
        {
            id: 'ANK-TRB-011',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_151141.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['black', 'yellow'],
            colorTags: ['black', 'yellow'],
            colorCombination: 'black & yellow',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-011',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-012',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_152233.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['black', 'yellow'],
            colorTags: ['black', 'yellow'],
            colorCombination: 'black & yellow',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-012',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-013',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_151042.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['black', 'yellow'],
            colorTags: ['black', 'yellow'],
            colorCombination: 'black & yellow',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-013',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-014',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_123038.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['red','blue','pink'],
            colorTags: ['red','blue','pink'],
            colorCombination: 'red & blue & pink',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-014',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-015',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_123348.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['red','blue','pink'],
            colorTags: ['red','blue','pink'],
            colorCombination: 'red & blue & pink',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-015',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-016',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_123611.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['blue','brown'],
            colorTags: ['blue','brown'],
            colorCombination: 'blue & brown',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-016',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-017',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_123722.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['blue','brown'],
            colorTags: ['blue','brown'],
            colorCombination: 'blue & brown',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-017',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-018',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_123819.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['pink','sky-blue','green'],
            colorTags: ['pink','sky-blue','green'],
            colorCombination: 'pink & sky-blue & green',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-018',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-019',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_124746.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['purple', 'blue'],
            colorTags: ['purple', 'blue'],
            colorCombination: 'purple & blue',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-019',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-020',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_124830.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['teal', 'black'],
            colorTags: ['teal', 'black'],
            colorCombination: 'teal & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-020',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-021',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_124913.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['green', 'purple'],
            colorTags: ['green', 'purple'],
            colorCombination: 'green & purple',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-021',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-022',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_125031.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['red', 'green'],
            colorTags: ['red', 'green'],
            colorCombination: 'red & green',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-022',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-023',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_125111.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['red', 'black'],
            colorTags: ['red', 'black'],
            colorCombination: 'red & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-023',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-024',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_125201.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['brown', 'cream'],
            colorTags: ['brown', 'cream'],
            colorCombination: 'brown & cream',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-024',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-025',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_125241.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['green', 'purple'],
            colorTags: ['green', 'purple'],
            colorCombination: 'green & purple',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-025',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-026',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_125428.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['orange', 'green'],
            colorTags: ['orange', 'green'],
            colorCombination: 'orange & green',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-026',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-027',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_125630.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['orange', 'blue'],
            colorTags: ['orange', 'blue'],
            colorCombination: 'orange & blue',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-027',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-028',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_144949.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['blue', 'orange'],
            colorTags: ['blue', 'orange'],
            colorCombination: 'blue & orange',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-028',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-029',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145103.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['black', 'pink'],
            colorTags: ['black', 'pink'],
            colorCombination: 'black & pink',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-029',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-030',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145200.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['purple', 'gold'],
            colorTags: ['purple', 'gold'],
            colorCombination: 'purple & gold',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-030',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-031',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145230.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['navy', 'red'],
            colorTags: ['navy', 'red'],
            colorCombination: 'navy & red',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-031',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-032',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145252.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['yellow', 'green'],
            colorTags: ['yellow', 'green'],
            colorCombination: 'yellow & green',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-032',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-033',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145327.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['teal', 'black'],
            colorTags: ['teal', 'black'],
            colorCombination: 'teal & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-033',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-034',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145416.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['orange', 'black'],
            colorTags: ['orange', 'black'],
            colorCombination: 'orange & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-034',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-035',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145445.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['red', 'white'],
            colorTags: ['red', 'white'],
            colorCombination: 'red & white',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-035',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-036',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145523.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['purple', 'teal'],
            colorTags: ['purple', 'teal'],
            colorCombination: 'purple & teal',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-036',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-037',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145553.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['yellow', 'black'],
            colorTags: ['yellow', 'black'],
            colorCombination: 'yellow & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-037',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-038',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145619.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['purple', 'black'],
            colorTags: ['purple', 'black'],
            colorCombination: 'purple & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-038',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-039',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145652.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['green', 'teal'],
            colorTags: ['green', 'teal'],
            colorCombination: 'green & teal',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-039',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-040',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145724.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['blue', 'yellow'],
            colorTags: ['blue', 'yellow'],
            colorCombination: 'blue & yellow',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-040',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-041',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145759.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['red', 'gold'],
            colorTags: ['red', 'gold'],
            colorCombination: 'red & gold',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-041',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-042',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145827.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['pink', 'black'],
            colorTags: ['pink', 'black'],
            colorCombination: 'pink & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-042',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-043',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145855.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['orange', 'blue'],
            colorTags: ['orange', 'blue'],
            colorCombination: 'orange & blue',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-043',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-044',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_145931.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['navy', 'gold'],
            colorTags: ['navy', 'gold'],
            colorCombination: 'navy & gold',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-044',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-045',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150031.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['green', 'black'],
            colorTags: ['green', 'black'],
            colorCombination: 'green & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-045',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-046',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150234.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['blue', 'orange'],
            colorTags: ['blue', 'orange'],
            colorCombination: 'blue & orange',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-046',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-047',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150307.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['purple', 'black'],
            colorTags: ['purple', 'black'],
            colorCombination: 'purple & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-047',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-048',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150349.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['yellow', 'black'],
            colorTags: ['yellow', 'black'],
            colorCombination: 'yellow & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-048',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-049',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150418.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['green', 'white'],
            colorTags: ['green', 'white'],
            colorCombination: 'green & white',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-049',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-050',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150506.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['teal', 'black'],
            colorTags: ['teal', 'black'],
            colorCombination: 'teal & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-050',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-051',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150546.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['navy', 'yellow'],
            colorTags: ['navy', 'yellow'],
            colorCombination: 'navy & yellow',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-051',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-052',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150621.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['red', 'black'],
            colorTags: ['red', 'black'],
            colorCombination: 'red & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-052',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-053',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150704.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['purple', 'yellow'],
            colorTags: ['purple', 'yellow'],
            colorCombination: 'purple & yellow',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-053',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-054',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150735.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['green', 'orange'],
            colorTags: ['green', 'orange'],
            colorCombination: 'green & orange',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-054',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-055',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150812.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['blue', 'white'],
            colorTags: ['blue', 'white'],
            colorCombination: 'blue & white',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-055',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-056',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_150845.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['pink', 'yellow'],
            colorTags: ['pink', 'yellow'],
            colorCombination: 'pink & yellow',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-056',
            pattern: 'Tribal'
        },
        {
            id: 'ANK-TRB-057',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_152233.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['yellow', 'black'],
            colorTags: ['yellow', 'black'],
            colorCombination: 'yellow & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-057',
            pattern: 'Tribal'
        },

        {
            id: 'ANK-TRB-066',
            name: 'Tribal Ankara Design 1',
            price: 20000,
            image: 'images/Ankara/Tribals/20260109_152233.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['yellow', 'black'],
            colorTags: ['yellow', 'black'],
            colorCombination: 'yellow & black',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-066',
            pattern: 'Tribal'
        },

        {
            id: 'ANK013',
            name: 'Cotonou Wax Design 1',
            price: 16000,
            image: 'images/ankara-cotonou.jpg',
            category: 'ankara',
            subcategory: 'Cotonou Wax',
            colors: ['blue', 'white'],
            colorTags: ['blue', 'white'],
            colorCombination: 'blue & white',
            description: 'Cotonou wax print Ankara fabric.',
            size: '6 yards',
            sku: 'ANK-CTN-013',
            pattern: 'Abstract'
        },
        {
            id: 'ANK014',
            name: 'Cotonou Wax Design 2',
            price: 16000,
            image: 'images/ankara-cotonou-2.jpg',
            category: 'ankara',
            subcategory: 'Cotonou Wax',
            colors: ['red', 'white', 'blue'],
            colorTags: ['red', 'white', 'blue'],
            colorCombination: 'red & white & blue',
            description: 'Cotonou wax with patriotic color scheme.',
            size: '6 yards',
            sku: 'ANK-CTN-014',
            pattern: 'Modern'
        },
        {
            id: 'ANK015',
            name: 'Medium Holland Design 1',
            price: 25000,
            image: 'images/ankara-holland.jpg',
            category: 'ankara',
            subcategory: 'Medium Holland',
            colors: ['purple', 'white'],
            colorTags: ['purple', 'white'],
            colorCombination: 'purple & white',
            description: 'Medium Holland wax Ankara fabric.',
            size: '6 yards',
            sku: 'ANK-MHL-015',
            pattern: 'Floral'
        },
        {
            id: 'ANK016',
            name: 'Medium Holland Design 2',
            price: 25000,
            image: 'images/ankara-holland-2.jpg',
            category: 'ankara',
            subcategory: 'Medium Holland',
            colors: ['pink', 'green', 'white'],
            colorTags: ['pink', 'green', 'white'],
            colorCombination: 'pink & green & white',
            description: 'Medium Holland with spring color palette.',
            size: '6 yards',
            sku: 'ANK-MHL-016',
            pattern: 'Floral'
        },
        {
            id: 'ANK017',
            name: 'Embellished Super-Wax',
            price: 30000,
            image: 'images/ankara-embellished.jpg',
            category: 'ankara',
            subcategory: 'Super Wax',
            colors: ['gold', 'black'],
            colorTags: ['gold', 'black'],
            colorCombination: 'gold & black',
            description: 'Super-wax Ankara with embellished patterns.',
            size: '6 yards',
            sku: 'ANK-ESW-017',
            pattern: 'Embellished'
        },
        {
            id: 'ANK018',
            name: 'Non-Embellished Super-Wax',
            price: 25000,
            image: 'images/ankara-superwax.jpg',
            category: 'ankara',
            subcategory: 'Super Wax',
            colors: ['blue', 'green'],
            colorTags: ['blue', 'green'],
            colorCombination: 'blue & green',
            description: 'Super-wax Ankara without embellishments.',
            size: '6 yards',
            sku: 'ANK-NSW-018',
            pattern: 'Abstract'
        },
        {
            id: 'ANK019',
            name: 'Kente Ankara Design 1',
            price: 25000,
            image: 'images/ankara-kente.jpg',
            category: 'ankara',
            subcategory: 'Kente',
            colors: ['red', 'yellow', 'green'],
            colorTags: ['red', 'yellow', 'green'],
            colorCombination: 'red & yellow & green',
            description: 'Ankara fabric with Kente cloth patterns.',
            size: '6 yards',
            sku: 'ANK-KNT-019',
            pattern: 'Kente'
        },
        {
            id: 'ANK020',
            name: 'Kente Ankara Design 2',
            price: 25000,
            image: 'images/ankara-kente-2.jpg',
            category: 'ankara',
            subcategory: 'Kente',
            colors: ['blue', 'yellow', 'white'],
            colorTags: ['blue', 'yellow', 'white'],
            colorCombination: 'blue & yellow & white',
            description: 'Kente-inspired Ankara with traditional patterns.',
            size: '6 yards',
            sku: 'ANK-KNT-020',
            pattern: 'Kente'
        },
        {
            id: 'ANK021',
            name: 'Medium Ankara Design 1',
            price: 7000,
            image: 'images/ankara-medium.jpg',
            category: 'ankara',
            subcategory: 'Medium',
            colors: ['pink', 'white'],
            colorTags: ['pink', 'white'],
            colorCombination: 'pink & white',
            description: 'Medium quality standard Ankara.',
            size: '6 yards',
            sku: 'ANK-MED-021',
            pattern: 'Floral'
        },
        {
            id: 'ANK022',
            name: 'Small Ankara Design 1',
            price: 5000,
            image: 'images/ankara-small.jpg',
            category: 'ankara',
            subcategory: 'Small',
            colors: ['green', 'white'],
            colorTags: ['green', 'white'],
            colorCombination: 'green & white',
            description: 'Small print Ankara fabric.',
            size: '6 yards',
            sku: 'ANK-SML-022',
            pattern: 'Mini'
        },
        {
            id: 'ANK023',
            name: 'Julius Embellished Design 1',
            price: 80000,
            image: 'images/ankara-julius.jpg',
            category: 'ankara',
            subcategory: 'Julius',
            colors: ['gold', 'black', 'red'],
            colorTags: ['gold', 'black', 'red'],
            colorCombination: 'gold & black & red',
            description: 'Premium Julius embellished Ankara.',
            size: '6 yards',
            sku: 'ANK-JLE-023',
            pattern: 'Embellished'
        },
        {
            id: 'ANK024',
            name: 'Julius Embellished Satin',
            price: 95000,
            image: 'images/ankara-julius-satin.jpg',
            category: 'ankara',
            subcategory: 'Julius',
            colors: ['silver', 'blue'],
            colorTags: ['silver', 'blue'],
            colorCombination: 'silver & blue',
            description: 'Julius embellished Ankara on satin base.',
            size: '6 yards',
            sku: 'ANK-JES-024',
            pattern: 'Embellished'
        },
        {
            id: 'ANK025',
            name: 'Super-Wax Exclusive',
            price: 180000,
            image: 'images/ankara-exclusive.jpg',
            category: 'ankara',
            subcategory: 'Super Wax',
            colors: ['black', 'red', 'gold'],
            colorTags: ['black', 'red', 'gold'],
            colorCombination: 'black & red & gold',
            description: 'Exclusive super-wax Ankara collection.',
            size: '6 yards',
            sku: 'ANK-SWE-025',
            pattern: 'Exclusive'
        },
        {
            id: 'ANK026',
            name: 'Julius Crystal Shine',
            price: 100000,
            image: 'images/ankara-crystal.jpg',
            category: 'ankara',
            subcategory: 'Julius',
            colors: ['blue', 'silver'],
            colorTags: ['blue', 'silver'],
            colorCombination: 'blue & silver',
            description: 'Julius Ankara with crystal shine effect.',
            size: '6 yards',
            sku: 'ANK-JCS-026',
            pattern: 'Crystal'
        },
        {
            id: 'ANK027',
            name: 'Dutch Super-Wax Design 1',
            price: 297000,
            image: 'images/ankara-dutch.jpg',
            category: 'ankara',
            subcategory: 'Dutch Wax',
            colors: ['white', 'gold', 'blue'],
            colorTags: ['white', 'gold', 'blue'],
            colorCombination: 'white & gold & blue',
            description: 'Premium Dutch super-wax Ankara.',
            size: '6 yards',
            sku: 'ANK-DSW-027',
            pattern: 'Premium'
        },
        {
            id: 'ANK028',
            name: 'Guaranteed Dutch Super-Wax',
            price: 176000,
            image: 'images/ankara-guaranteed.jpg',
            category: 'ankara',
            subcategory: 'Dutch Wax',
            colors: ['gold', 'blue', 'black'],
            colorTags: ['gold', 'blue', 'black'],
            colorCombination: 'gold & blue & black',
            description: 'Guaranteed Dutch super-wax (6 yards).',
            size: '6 yards',
            sku: 'ANK-GDS-028',
            pattern: 'Premium'
        },
        {
            id: 'ANK029',
            name: 'Guaranteed Dutch Super-Wax (4 yards)',
            price: 117500,
            image: 'images/ankara-guaranteed-4yd.jpg',
            category: 'ankara',
            subcategory: 'Dutch Wax',
            colors: ['gold', 'black'],
            colorTags: ['gold', 'black'],
            colorCombination: 'gold & black',
            description: 'Guaranteed Dutch super-wax (4 yards).',
            size: '4 yards',
            sku: 'ANK-GD4-029',
            pattern: 'Premium'
        },
        {
            id: 'ANK030',
            name: 'Guaranteed Dutch Super-Wax Embellished',
            price: 226000,
            image: 'images/ankara-guaranteed-emb.jpg',
            category: 'ankara',
            subcategory: 'Dutch Wax',
            colors: ['gold', 'red', 'purple'],
            colorTags: ['gold', 'red', 'purple'],
            colorCombination: 'gold & red & purple',
            description: 'Embellished guaranteed Dutch super-wax.',
            size: '6 yards',
            sku: 'ANK-GDE-030',
            pattern: 'Embellished'
        }
    ],

    // Brocades Products (10 yards per piece)
    brocades: [
        {
            id: 'BRO-TXM-002',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/Brocades/Texil Magic Plain/20260116_121223.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['silver'],
            colorTags: ['silver'],
            colorCombination: 'silver',
            description: 'Texil Magic brocade fabric.',
            size: '10 yards',
            sku: 'BRO-TXM-002',
            pattern: 'Royal'
        },

        {
            id: 'BRO-TXM-003',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/Brocades/Texil Magic Plain/20260116_121407.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['sky blue'],
            colorTags: ['sky blue'],
            colorCombination: 'sky blue',
            description: 'Texil Magic brocade fabric.',
            size: '10 yards',
            sku: 'BRO-TXM-003',
            pattern: 'Royal'
        },

        {
            id: 'BRO-TXM-004',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/Brocades/Texil Magic Plain/20260116_121437.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['silver'],
            colorTags: ['silver'],
            colorCombination: 'silver',
            description: 'Texil Magic brocade fabric.',
            size: '10 yards',
            sku: 'BRO-TXM-004',
            pattern: 'Royal'
        },

        {
            id: 'BRO-TXM-005',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/Brocades/Texil Magic Plain/20260116_121805.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['purple'],
            colorTags: ['purple'],
            colorCombination: 'purple',
            description: 'Texil Magic brocade fabric.',
            size: '10 yards',
            sku: 'BRO-TXM-005',
            pattern: 'Royal'
        },

        {
            id: 'BRO-TXM-006',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/Brocades/Texil Magic Plain/20260116_121825.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['light blue'],
            colorTags: ['light blue'],
            colorCombination: 'light blue',
            description: 'Texil Magic brocade fabric.',
            size: '10 yards',
            sku: 'BRO-TXM-006',
            pattern: 'Royal'
        },

        {
            id: 'BRO-TXM-007',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/Brocades/Texil Magic Plain/20260116_121904.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['gold'],
            colorTags: ['gold'],
            colorCombination: 'gold',
            description: 'Texil Magic brocade fabric.',
            size: '10 yards',
            sku: 'BRO-TXM-007',
            pattern: 'Royal'
        },

        {
            id: 'BRO-TXM-008',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/Brocades/Texil Magic Plain/20260116_121931.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['onion-purple'],
            colorTags: ['onion-purple'],
            colorCombination: 'onion-purple',
            description: 'Texil Magic brocade fabric.',
            size: '10 yards',
            sku: 'BRO-TXM-008',
            pattern: 'Royal'
        },

        {
            id: 'BRO-TXM-009',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/Brocades/Texil Magic Plain/20260116_121953.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['cream'],
            colorTags: ['cream'],
            colorCombination: 'cream',
            description: 'Texil Magic brocade fabric.',
            size: '10 yards',
            sku: 'BRO-TXM-009',
            pattern: 'Royal'
        },

        {
            id: 'BRO-VEL-005',
            name: 'Victoria Elite Brocade',
            price: 250000,
            image: 'images/Brocades/Victoria Elite/20260116_123544.jpg',
            category: 'brocades',
            subcategory: 'Victoria Elite',
            colors: ['purple'],
            colorTags: ['purple'],
            colorCombination: 'purple',
            description: 'Premium Victoria Elite brocade.',
            size: '10 yards',
            sku: 'BRO-VEL-005',
            pattern: 'Elite'
        }, 
        {
            id: 'BRO-VEL-006',
            name: 'Victoria Elite Brocade',
            price: 250000,
            image: 'images/Brocades/Victoria Elite/20260116_123353.jpg',
            category: 'brocades',
            subcategory: 'Victoria Elite',
            colors: ['silver'],
            colorTags: ['silver'],
            colorCombination: 'silver',
            description: 'Premium Victoria Elite brocade.',
            size: '10 yards',
            sku: 'BRO-VEL-006',
            pattern: 'Elite'
        },
        {
            id: 'BRO-VEL-007',
            name: 'Victoria Elite Brocade',
            price: 250000,
            image: 'images/Brocades/Victoria Elite/20260116_123212.jpg',
            category: 'brocades',
            subcategory: 'Victoria Elite',
            colors: ['green'],
            colorTags: ['green'],
            colorCombination: 'green',
            description: 'Premium Victoria Elite brocade.',
            size: '10 yards',
            sku: 'BRO-VEL-007',
            pattern: 'Elite'
        },
        {
            id: 'BRO-VRO-008',
            name: 'Victoria Royal Brocade',
            price: 220000,
            image: 'images/Brocades/Victoria Elite/20260116_122914.jpg',
            category: 'brocades',
            subcategory: 'Victoria Royal',
            colors: ['white'],
            colorTags: ['white'],
            colorCombination: 'white',
            description: 'Premium Victoria Royal brocade.',
            size: '10 yards',
            sku: 'BRO-VRO-008',
            pattern: 'Royal'
        },
        {
            id: 'BRO-GTM-014',
            name: 'Getzener Magnum Brocade',
            price: 250000,
            image: 'images/Brocades/Getzner Magnum/mint-green.jpg',
            category: 'brocades',
            subcategory: 'Getzener Magnum',
            colors: ['mint-green'],
            colorTags: ['mint-green'],
            colorCombination: 'mint-green',
            description: 'Getzener Magnum brocade.',
            size: '10 yards',
            sku: 'BRO-GTM-014',
            pattern: 'Magnum'
        },
        {
            id: 'BRO-GTM-018',
            name: 'Getzener Magnum Brocade',
            price: 250000,
            image: 'images/Brocades/Getzner Magnum/light-blue.jpg',
            category: 'brocades',
            subcategory: 'Getzener Magnum',
            colors: ['light-blue'],
            colorTags: ['light-blue'],
            colorCombination: 'light-blue',
            description: 'Getzener Magnum brocade.',
            size: '10 yards',
            sku: 'BRO-GTM-018',
            pattern: 'Magnum'
        },
        {
            id: 'BRO-GTM-017',
            name: 'Getzener Magnum Brocade',
            price: 250000,
            image: 'images/Brocades/Getzner Magnum/deep-grey.jpg',
            category: 'brocades',
            subcategory: 'Getzener Magnum',
            colors: ['deep-grey'],
            colorTags: ['deep-grey'],
            colorCombination: 'deep-grey',
            description: 'Getzener Magnum brocade.',
            size: '10 yards',
            sku: 'BRO-GTM-017',
            pattern: 'Magnum'
        },
        {
            id: 'BRO-GTM-016',
            name: 'Getzener Magnum Brocade',
            price: 250000,
            image: 'images/Brocades/Getzner Magnum/egg-yellow.jpg',
            category: 'brocades',
            subcategory: 'Getzener Magnum',
            colors: ['egg-yellow'],
            colorTags: ['egg-yellow'],
            colorCombination: 'egg-yellow',
            description: 'Getzener Magnum brocade.',
            size: '10 yards',
            sku: 'BRO-GTM-016',
            pattern: 'Magnum'
        },
        {
            id: 'BRO-GTM-015',
            name: 'Getzener Magnum Brocade',
            price: 250000,
            image: 'images/Brocades/Getzner Magnum/brown.jpg',
            category: 'brocades',
            subcategory: 'Getzener Magnum',
            colors: ['brown'],
            colorTags: ['brown'],
            colorCombination: 'brown',
            description: 'Getzener Magnum brocade.',
            size: '10 yards',
            sku: 'BRO-GTM-015',
            pattern: 'Magnum'
        },
        {
            id: 'BRO-GTX-009',
            name: 'Getzner Texil Magic (Plain)',
            price: 100000,
            image: 'images/Brocades/Getzner Texil Magic (Plain)/20260116_125308.jpg',
            category: 'brocades',
            subcategory: 'Getzener Texil',
            colors: ['pink', 'black'],
            colorTags: ['pink', 'black'],
            colorCombination: 'pink & black',
            description: 'Getzener Texil brocade fabric.',
            size: '10 yards',
            sku: 'BRO-GTX-009',
            pattern: 'Modern'
        },

        {
            id: 'BRO-GTX-010',
            name: 'Getzner Texil Magic (Plain)',
            price: 100000,
            image: 'images/Brocades/Getzner Texil Magic (Plain)/20260116_125319.jpg',
            category: 'brocades',
            subcategory: 'Getzener Texil',
            colors: ['yellow', 'blue'],
            colorTags: ['yellow', 'blue'],
            colorCombination: 'yellow & blue',
            description: 'Getzener Texil brocade fabric.',
            size: '10 yards',
            sku: 'BRO-GTX-010',
            pattern: 'Modern'
        },

        {
            id: 'BRO-GTX-011',
            name: 'Getzner Texil Magic (Plain)',
            price: 100000,
            image: 'images/Brocades/Getzner Texil Magic (Plain)/20260116_125327.jpg',
            category: 'brocades',
            subcategory: 'Getzener Texil',
            colors: ['red', 'blue'],
            colorTags: ['red', 'blue'],
            colorCombination: 'red & blue',
            description: 'Getzener Texil brocade fabric.',
            size: '10 yards',
            sku: 'BRO-GTX-011',
            pattern: 'Modern'
        },

        {
            id: 'BRO-GTX-012',
            name: 'Getzner Texil Magic (Plain)',
            price: 100000,
            image: 'images/Brocades/Getzner Texil Magic (Plain)/20260116_125350.jpg',
            category: 'brocades',
            subcategory: 'Getzener Texil',
            colors: ['gold', 'white'],
            colorTags: ['gold', 'white'],
            colorCombination: 'gold & white',
            description: 'Getzener Texil brocade fabric.',
            size: '10 yards',
            sku: 'BRO-GTX-012',
            pattern: 'Modern'
        },

        {
            id: 'BRO-GTX-013',
            name: 'Getzner Texil Magic (Plain)',
            price: 100000,
            image: 'images/Brocades/Getzner Texil Magic (Plain)/20260116_125425.jpg',
            category: 'brocades',
            subcategory: 'Getzener Texil',
            colors: ['red', 'pink'],
            colorTags: ['red', 'pink'],
            colorCombination: 'red & pink',
            description: 'Getzener Texil brocade fabric.',
            size: '10 yards',
            sku: 'BRO-GTX-013',
            pattern: 'Modern'
        },
        {
                id: 'BRO-GGL-009',
                name: 'Getzner Texil Magic (Ladies Brocades - 2 in 1)',
                price: 100000,
                image: 'images/Brocades/Getzner Texil Magic (Ladies Brocades - 2 in 1)/20260116_124731.jpg',
                category: 'brocades',
                subcategory: 'Getzener Gold',
                colors: ['blue', 'gold', 'multicolor'],
                colorTags: ['blue', 'gold', 'multicolor'],
                colorCombination: 'blue & gold',
                description: 'Getzener Gold ladies brocade.',
                size: '10 yards',
                sku: 'BRO-GGL-009',
                pattern: 'Gold'
        },
        {
                id: 'BRO-GGL-010',
                name: 'Getzner Texil Magic (Ladies Brocades - 2 in 1)',
                price: 100000,
                image: 'images/Brocades/Getzner Texil Magic (Ladies Brocades - 2 in 1)/20260116_124744.jpg',
                category: 'brocades',
                subcategory: 'Getzener Gold',
                colors: ['purple', 'gold', 'white'],
                colorTags: ['purple', 'gold', 'white'],
                colorCombination: 'purple & gold',
                description: 'Getzener Gold ladies brocade.',
                size: '10 yards',
                sku: 'BRO-GGL-010',
                pattern: 'Gold'
        },
        {
                id: 'BRO-GGL-011',
                name: 'Getzner Texil Magic (Ladies Brocades - 2 in 1)',
                price: 100000,
                image: 'images/Brocades/Getzner Texil Magic (Ladies Brocades - 2 in 1)/20260116_124758.jpg',
                category: 'brocades',
                subcategory: 'Getzener Gold',
                colors: ['lavender', 'white', 'gold'],
                colorTags: ['lavender', 'white', 'gold'],
                colorCombination: 'lavender & white',
                description: 'Getzener Gold ladies brocade.',
                size: '10 yards',
                sku: 'BRO-GGL-011',
                pattern: 'Gold'
        },
        {
                id: 'BRO-GGL-012',
                name: 'Getzner Texil Magic (Ladies Brocades - 2 in 1)',
                price: 100000,
                image: 'images/Brocades/Getzner Texil Magic (Ladies Brocades - 2 in 1)/20260116_124808.jpg',
                category: 'brocades',
                subcategory: 'Getzener Gold',
                colors: ['blue', 'gold', 'multicolor'],
                colorTags: ['blue', 'gold', 'multicolor'],
                colorCombination: 'blue & gold',
                description: 'Getzener Gold ladies brocade.',
                size: '10 yards',
                sku: 'BRO-GGL-012',
                pattern: 'Gold'
        },
        {
                id: 'BRO-GGL-013',
                name: 'Getzner Texil Magic (Ladies Brocades - 2 in 1)',
                price: 100000,
                image: 'images/Brocades/Getzner Texil Magic (Ladies Brocades - 2 in 1)/20260116_124819.jpg',
                category: 'brocades',
                subcategory: 'Getzener Gold',
                colors: ['green', 'beige', 'gold'],
                colorTags: ['green', 'beige', 'gold'],
                colorCombination: 'green & beige',
                description: 'Getzener Gold ladies brocade.',
                size: '10 yards',
                sku: 'BRO-GGL-013',
                pattern: 'Gold'
        },
        {
                id: 'BRO-GGL-014',
                name: 'Getzner Texil Magic (Ladies Brocades - 2 in 1)',
                price: 100000,
                image: 'images/Brocades/Getzner Texil Magic (Ladies Brocades - 2 in 1)/20260116_124832.jpg',
                category: 'brocades',
                subcategory: 'Getzener Gold',
                colors: ['orange', 'cream', 'purple'],
                colorTags: ['orange', 'cream', 'purple'],
                colorCombination: 'orange & cream',
                description: 'Getzener Gold ladies brocade.',
                size: '10 yards',
                sku: 'BRO-GGL-014',
                pattern: 'Gold'
        },
        {
                id: 'BRO-GGL-015',
                name: 'Getzner Texil Magic (Ladies Brocades - 2 in 1)',
                price: 100000,
                image: 'images/Brocades/Getzner Texil Magic (Ladies Brocades - 2 in 1)/20260116_124844.jpg',
                category: 'brocades',
                subcategory: 'Getzener Gold',
                colors: ['green', 'multicolor', 'gold'],
                colorTags: ['green', 'multicolor', 'gold'],
                colorCombination: 'green & gold',
                description: 'Getzener Gold ladies brocade.',
                size: '10 yards',
                sku: 'BRO-GGL-015',
                pattern: 'Gold'
        },
        {
                id: 'BRO-GGL-016',
                name: 'Getzner Texil Magic (Ladies Brocades - 2 in 1)',
                price: 100000,
                image: 'images/Brocades/Getzner Texil Magic (Ladies Brocades - 2 in 1)/20260116_124854.jpg',
                category: 'brocades',
                subcategory: 'Getzener Gold',
                colors: ['beige', 'blue', 'gold'],
                colorTags: ['beige', 'blue', 'gold'],
                colorCombination: 'beige & blue',
                description: 'Getzener Gold ladies brocade.',
                size: '10 yards',
                sku: 'BRO-GGL-016',
                pattern: 'Gold'
        }
    ],

    // Adires Products
    adires: [
        {
            id: 'ADI001',
            name: 'Glossy Adire Design 1',
            price: 5000,
            image: 'images/adire-glossy.jpg',
            category: 'adires',
            subcategory: 'Glossy',
            colors: ['blue', 'white'],
            colorTags: ['blue', 'white'],
            colorCombination: 'blue & white',
            description: 'Glossy finish Adire fabric.',
            size: '6 yards',
            sku: 'ADI-GLS-001',
            pattern: 'Traditional'
        },
        {
            id: 'ADI002',
            name: 'Glossy Adire Design 2',
            price: 5000,
            image: 'images/adire-glossy-2.jpg',
            category: 'adires',
            subcategory: 'Glossy',
            colors: ['indigo', 'white'],
            colorTags: ['indigo', 'white'],
            colorCombination: 'indigo & white',
            description: 'Deep indigo glossy Adire.',
            size: '6 yards',
            sku: 'ADI-GLS-002',
            pattern: 'Geometric'
        },
        {
            id: 'ADI003',
            name: 'Cotton Adire Design 1',
            price: 16000,
            image: 'images/adire-cotton.jpg',
            category: 'adires',
            subcategory: 'Cotton',
            colors: ['indigo', 'white'],
            colorTags: ['indigo', 'white'],
            colorCombination: 'indigo & white',
            description: 'Pure cotton Adire fabric.',
            size: '6 yards',
            sku: 'ADI-COT-003',
            pattern: 'Traditional'
        },
        {
            id: 'ADI004',
            name: 'Cotton Adire Design 2',
            price: 16000,
            image: 'images/adire-cotton-2.jpg',
            category: 'adires',
            subcategory: 'Cotton',
            colors: ['blue', 'brown'],
            colorTags: ['blue', 'brown'],
            colorCombination: 'blue & brown',
            description: 'Cotton Adire with blue and brown patterns.',
            size: '6 yards',
            sku: 'ADI-COT-004',
            pattern: 'Ethnic'
        },
        {
            id: 'ADI005',
            name: 'Adire Wax Design 1',
            price: 16000,
            image: 'images/adire-wax.jpg',
            category: 'adires',
            subcategory: 'Wax',
            colors: ['blue', 'yellow'],
            colorTags: ['blue', 'yellow'],
            colorCombination: 'blue & yellow',
            description: 'Adire with wax print patterns.',
            size: '6 yards',
            sku: 'ADI-WAX-005',
            pattern: 'Modern'
        },
        {
            id: 'ADI006',
            name: 'Adire Wax Design 2',
            price: 16000,
            image: 'images/adire-wax-2.jpg',
            category: 'adires',
            subcategory: 'Wax',
            colors: ['green', 'white', 'black'],
            colorTags: ['green', 'white', 'black'],
            colorCombination: 'green & white & black',
            description: 'Wax Adire with bold patterns.',
            size: '6 yards',
            sku: 'ADI-WAX-006',
            pattern: 'Abstract'
        }
    ],

    // Undivided Categories - Sample Products
    laces: [
        {
            id: 'LAC001',
            name: 'French Lace Design 1',
            price: 35000,
            image: 'images/lace-french.jpg',
            category: 'laces',
            subcategory: 'French',
            colors: ['white', 'ivory'],
            colorTags: ['white', 'ivory'],
            colorCombination: 'white & ivory',
            description: 'Premium French lace fabric.',
            size: '3 yards',
            sku: 'LAC-FRE-001',
            pattern: 'Floral'
        },
        {
            id: 'LAC002',
            name: 'French Lace Design 2',
            price: 35000,
            image: 'images/lace-french-2.jpg',
            category: 'laces',
            subcategory: 'French',
            colors: ['ivory'],
            colorTags: ['ivory'],
            colorCombination: 'ivory',
            description: 'Elegant ivory French lace.',
            size: '3 yards',
            sku: 'LAC-FRE-002',
            pattern: 'Delicate'
        },
        {
            id: 'LAC003',
            name: 'Swiss Lace Design 1',
            price: 42000,
            image: 'images/lace-swiss.jpg',
            category: 'laces',
            subcategory: 'Swiss',
            colors: ['white'],
            colorTags: ['white'],
            colorCombination: 'white',
            description: 'High-quality Swiss lace.',
            size: '3 yards',
            sku: 'LAC-SWI-003',
            pattern: 'Intricate'
        },
        {
            id: 'LAC004',
            name: 'Swiss Lace Design 2',
            price: 42000,
            image: 'images/lace-swiss-2.jpg',
            category: 'laces',
            subcategory: 'Swiss',
            colors: ['ivory'],
            colorTags: ['ivory'],
            colorCombination: 'ivory',
            description: 'Premium Swiss lace with intricate design.',
            size: '3 yards',
            sku: 'LAC-SWI-004',
            pattern: 'Premium'
        }
    ],

    asooke: [
        {
            id: 'ASO001',
            name: 'Traditional Aso-oke Design 1',
            price: 45000,
            image: 'images/asooke-traditional.jpg',
            category: 'asooke',
            subcategory: 'Traditional',
            colors: ['brown', 'gold'],
            colorTags: ['brown', 'gold'],
            colorCombination: 'brown & gold',
            description: 'Traditional handwoven Aso-oke.',
            size: '5 yards',
            sku: 'ASO-TRD-001',
            pattern: 'Traditional'
        },
        {
            id: 'ASO002',
            name: 'Traditional Aso-oke Design 2',
            price: 45000,
            image: 'images/asooke-traditional-2.jpg',
            category: 'asooke',
            subcategory: 'Traditional',
            colors: ['red', 'gold', 'green'],
            colorTags: ['red', 'gold', 'green'],
            colorCombination: 'red & gold & green',
            description: 'Vibrant traditional Aso-oke.',
            size: '5 yards',
            sku: 'ASO-TRD-002',
            pattern: 'Ethnic'
        },
        {
            id: 'ASO003',
            name: 'Modern Aso-oke Design 1',
            price: 38000,
            image: 'images/asooke-modern.jpg',
            category: 'asooke',
            subcategory: 'Modern',
            colors: ['black', 'silver'],
            colorTags: ['black', 'silver'],
            colorCombination: 'black & silver',
            description: 'Modern design Aso-oke.',
            size: '5 yards',
            sku: 'ASO-MOD-003',
            pattern: 'Modern'
        },
        {
            id: 'ASO004',
            name: 'Modern Aso-oke Design 2',
            price: 38000,
            image: 'images/asooke-modern-2.jpg',
            category: 'asooke',
            subcategory: 'Modern',
            colors: ['blue', 'silver', 'white'],
            colorTags: ['blue', 'silver', 'white'],
            colorCombination: 'blue & silver & white',
            description: 'Contemporary Aso-oke design.',
            size: '5 yards',
            sku: 'ASO-MOD-004',
            pattern: 'Contemporary'
        }
    ],

    // Featured Products for Homepage
    featured: [
        {
            id: 'ANK001',
            name: 'Hitarget Ankara',
            price: 15000,
            image: 'images/ankara-hitarget.jpg',
            category: 'ankara'
        },
        {
            id: 'BRO001',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/brocade-texil.jpg',
            category: 'brocades'
        },
        {
            id: 'ADI001',
            name: 'Glossy Adire',
            price: 5000,
            image: 'images/adire-glossy.jpg',
            category: 'adires'
        },
        {
            id: 'LAC001',
            name: 'French Lace',
            price: 35000,
            image: 'images/lace-french.jpg',
            category: 'laces'
        }
    ]
};

// Helper function to get all products
function getAllProducts() {
    let allProducts = [];
    for (const category in productsData) {
        if (category !== 'featured') {
            allProducts = allProducts.concat(productsData[category]);
        }
    }
    return allProducts;
}

// Helper function to format price
function formatPrice(price) {
    return `₦${price.toLocaleString('en-NG')}`;
}
