// Products Data for Ai-oko Fabrics Store
const productsData = {
    // Ankara Products (6 yards per piece)
    ankara: [
        {
            id: 'ANK001',
            name: 'Hitarget Ankara Design 1',
            price: 15000,
            image: 'images/ankara-hitarget.jpg',
            category: 'ankara',
            subcategory: 'Hitarget',
            colors: ['red', 'blue', 'yellow'],
            colorTags: ['red', 'blue', 'yellow'],
            colorCombination: 'red & blue & yellow',
            description: 'Premium Hitarget Ankara fabric with vibrant colors and patterns.',
            size: '6 yards',
            sku: 'ANK-HTG-001',
            pattern: 'Geometric'
        },
        {
            id: 'ANK002',
            name: 'Hitarget Ankara Design 2',
            price: 15000,
            image: 'images/ankara-hitarget-2.jpg',
            category: 'ankara',
            subcategory: 'Hitarget',
            colors: ['green', 'blue'],
            colorTags: ['green', 'blue'],
            colorCombination: 'green & blue',
            description: 'Hitarget Ankara with green and blue geometric patterns.',
            size: '6 yards',
            sku: 'ANK-HTG-002',
            pattern: 'Geometric'
        },
        {
            id: 'ANK003',
            name: 'Hitarget Ankara Design 3',
            price: 15000,
            image: 'images/ankara-hitarget-3.jpg',
            category: 'ankara',
            subcategory: 'Hitarget',
            colors: ['red', 'black', 'white'],
            colorTags: ['red', 'black', 'white'],
            colorCombination: 'red & black & white',
            description: 'Hitarget Ankara with contrasting red, black, and white design.',
            size: '6 yards',
            sku: 'ANK-HTG-003',
            pattern: 'Abstract'
        },
        {
            id: 'ANK004',
            name: 'Hitarget Ankara Design 4',
            price: 15000,
            image: 'images/ankara-hitarget-4.jpg',
            category: 'ankara',
            subcategory: 'Hitarget',
            colors: ['purple', 'gold'],
            colorTags: ['purple', 'gold'],
            colorCombination: 'purple & gold',
            description: 'Elegant Hitarget Ankara with purple and gold royal patterns.',
            size: '6 yards',
            sku: 'ANK-HTG-004',
            pattern: 'Traditional'
        },
        {
            id: 'ANK005',
            name: 'Medium Chingavy Design 1',
            price: 15000,
            image: 'images/ankara-chingavy.jpg',
            category: 'ankara',
            subcategory: 'Medium Chingavy',
            colors: ['green', 'blue'],
            colorTags: ['green', 'blue'],
            colorCombination: 'green & blue',
            description: 'Medium quality Chingavy fabric with intricate patterns.',
            size: '6 yards',
            sku: 'ANK-MCH-005',
            pattern: 'Floral'
        },
        {
            id: 'ANK006',
            name: 'Medium Chingavy Design 2',
            price: 15000,
            image: 'images/ankara-chingavy-2.jpg',
            category: 'ankara',
            subcategory: 'Medium Chingavy',
            colors: ['red', 'yellow', 'black'],
            colorTags: ['red', 'yellow', 'black'],
            colorCombination: 'red & yellow & black',
            description: 'Vibrant Chingavy with traditional Nigerian patterns.',
            size: '6 yards',
            sku: 'ANK-MCH-006',
            pattern: 'Traditional'
        },
        {
            id: 'ANK007',
            name: 'Mali Ankara Design 1',
            price: 25000,
            image: 'images/ankara-mali.jpg',
            category: 'ankara',
            subcategory: 'Mali',
            colors: ['red', 'black'],
            colorTags: ['red', 'black'],
            colorCombination: 'red & black',
            description: 'High-quality Mali Ankara with premium wax prints.',
            size: '6 yards',
            sku: 'ANK-MAL-007',
            pattern: 'Abstract'
        },
        {
            id: 'ANK008',
            name: 'Mali Ankara Design 2',
            price: 25000,
            image: 'images/ankara-mali-2.jpg',
            category: 'ankara',
            subcategory: 'Mali',
            colors: ['blue', 'gold', 'white'],
            colorTags: ['blue', 'gold', 'white'],
            colorCombination: 'blue & gold & white',
            description: 'Premium Mali Ankara with blue and gold accents.',
            size: '6 yards',
            sku: 'ANK-MAL-008',
            pattern: 'Geometric'
        },
        {
            id: 'ANK009',
            name: 'Akwete Ankara Design 1',
            price: 17000,
            image: 'images/ankara-akwete.jpg',
            category: 'ankara',
            subcategory: 'Akwete',
            colors: ['brown', 'orange'],
            colorTags: ['brown', 'orange'],
            colorCombination: 'brown & orange',
            description: 'Traditional Akwete design Ankara fabric.',
            size: '6 yards',
            sku: 'ANK-AKW-009',
            pattern: 'Traditional'
        },
        {
            id: 'ANK010',
            name: 'Akwete Ankara Design 2',
            price: 17000,
            image: 'images/ankara-akwete-2.jpg',
            category: 'ankara',
            subcategory: 'Akwete',
            colors: ['green', 'yellow', 'brown'],
            colorTags: ['green', 'yellow', 'brown'],
            colorCombination: 'green & yellow & brown',
            description: 'Akwete Ankara with earthy tones and patterns.',
            size: '6 yards',
            sku: 'ANK-AKW-010',
            pattern: 'Ethnic'
        },
        {
            id: 'ANK011',
            name: 'Tribal Ankara Design 1',
            price: 23000,
            image: 'images/ankara-tribal.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['black', 'yellow'],
            colorTags: ['black', 'yellow'],
            colorCombination: 'black & yellow',
            description: 'Tribal pattern Ankara with cultural motifs.',
            size: '6 yards',
            sku: 'ANK-TRB-011',
            pattern: 'Tribal'
        },
        {
            id: 'ANK012',
            name: 'Tribal Ankara Design 2',
            price: 23000,
            image: 'images/ankara-tribal-2.jpg',
            category: 'ankara',
            subcategory: 'Tribal',
            colors: ['red', 'white', 'black'],
            colorTags: ['red', 'white', 'black'],
            colorCombination: 'red & white & black',
            description: 'Vibrant tribal Ankara with bold patterns.',
            size: '6 yards',
            sku: 'ANK-TRB-012',
            pattern: 'Tribal'
        },
        {
            id: 'ANK013',
            name: 'Cotonou Wax Design 1',
            price: 16000,
            image: 'images/ankara-cotonou.jpg',
            category: 'ankara',
            subcategory: 'Cotonou Wax',
            colors: ['blue', 'white'],
            colorTags: ['blue', 'white'],
            colorCombination: 'blue & white',
            description: 'Cotonou wax print Ankara fabric.',
            size: '6 yards',
            sku: 'ANK-CTN-013',
            pattern: 'Abstract'
        },
        {
            id: 'ANK014',
            name: 'Cotonou Wax Design 2',
            price: 16000,
            image: 'images/ankara-cotonou-2.jpg',
            category: 'ankara',
            subcategory: 'Cotonou Wax',
            colors: ['red', 'white', 'blue'],
            colorTags: ['red', 'white', 'blue'],
            colorCombination: 'red & white & blue',
            description: 'Cotonou wax with patriotic color scheme.',
            size: '6 yards',
            sku: 'ANK-CTN-014',
            pattern: 'Modern'
        },
        {
            id: 'ANK015',
            name: 'Medium Holland Design 1',
            price: 25000,
            image: 'images/ankara-holland.jpg',
            category: 'ankara',
            subcategory: 'Medium Holland',
            colors: ['purple', 'white'],
            colorTags: ['purple', 'white'],
            colorCombination: 'purple & white',
            description: 'Medium Holland wax Ankara fabric.',
            size: '6 yards',
            sku: 'ANK-MHL-015',
            pattern: 'Floral'
        },
        {
            id: 'ANK016',
            name: 'Medium Holland Design 2',
            price: 25000,
            image: 'images/ankara-holland-2.jpg',
            category: 'ankara',
            subcategory: 'Medium Holland',
            colors: ['pink', 'green', 'white'],
            colorTags: ['pink', 'green', 'white'],
            colorCombination: 'pink & green & white',
            description: 'Medium Holland with spring color palette.',
            size: '6 yards',
            sku: 'ANK-MHL-016',
            pattern: 'Floral'
        },
        {
            id: 'ANK017',
            name: 'Embellished Super-Wax',
            price: 30000,
            image: 'images/ankara-embellished.jpg',
            category: 'ankara',
            subcategory: 'Super Wax',
            colors: ['gold', 'black'],
            colorTags: ['gold', 'black'],
            colorCombination: 'gold & black',
            description: 'Super-wax Ankara with embellished patterns.',
            size: '6 yards',
            sku: 'ANK-ESW-017',
            pattern: 'Embellished'
        },
        {
            id: 'ANK018',
            name: 'Non-Embellished Super-Wax',
            price: 25000,
            image: 'images/ankara-superwax.jpg',
            category: 'ankara',
            subcategory: 'Super Wax',
            colors: ['blue', 'green'],
            colorTags: ['blue', 'green'],
            colorCombination: 'blue & green',
            description: 'Super-wax Ankara without embellishments.',
            size: '6 yards',
            sku: 'ANK-NSW-018',
            pattern: 'Abstract'
        },
        {
            id: 'ANK019',
            name: 'Kente Ankara Design 1',
            price: 25000,
            image: 'images/ankara-kente.jpg',
            category: 'ankara',
            subcategory: 'Kente',
            colors: ['red', 'yellow', 'green'],
            colorTags: ['red', 'yellow', 'green'],
            colorCombination: 'red & yellow & green',
            description: 'Ankara fabric with Kente cloth patterns.',
            size: '6 yards',
            sku: 'ANK-KNT-019',
            pattern: 'Kente'
        },
        {
            id: 'ANK020',
            name: 'Kente Ankara Design 2',
            price: 25000,
            image: 'images/ankara-kente-2.jpg',
            category: 'ankara',
            subcategory: 'Kente',
            colors: ['blue', 'yellow', 'white'],
            colorTags: ['blue', 'yellow', 'white'],
            colorCombination: 'blue & yellow & white',
            description: 'Kente-inspired Ankara with traditional patterns.',
            size: '6 yards',
            sku: 'ANK-KNT-020',
            pattern: 'Kente'
        },
        {
            id: 'ANK021',
            name: 'Medium Ankara Design 1',
            price: 7000,
            image: 'images/ankara-medium.jpg',
            category: 'ankara',
            subcategory: 'Medium',
            colors: ['pink', 'white'],
            colorTags: ['pink', 'white'],
            colorCombination: 'pink & white',
            description: 'Medium quality standard Ankara.',
            size: '6 yards',
            sku: 'ANK-MED-021',
            pattern: 'Floral'
        },
        {
            id: 'ANK022',
            name: 'Small Ankara Design 1',
            price: 5000,
            image: 'images/ankara-small.jpg',
            category: 'ankara',
            subcategory: 'Small',
            colors: ['green', 'white'],
            colorTags: ['green', 'white'],
            colorCombination: 'green & white',
            description: 'Small print Ankara fabric.',
            size: '6 yards',
            sku: 'ANK-SML-022',
            pattern: 'Mini'
        },
        {
            id: 'ANK023',
            name: 'Julius Embellished Design 1',
            price: 80000,
            image: 'images/ankara-julius.jpg',
            category: 'ankara',
            subcategory: 'Julius',
            colors: ['gold', 'black', 'red'],
            colorTags: ['gold', 'black', 'red'],
            colorCombination: 'gold & black & red',
            description: 'Premium Julius embellished Ankara.',
            size: '6 yards',
            sku: 'ANK-JLE-023',
            pattern: 'Embellished'
        },
        {
            id: 'ANK024',
            name: 'Julius Embellished Satin',
            price: 95000,
            image: 'images/ankara-julius-satin.jpg',
            category: 'ankara',
            subcategory: 'Julius',
            colors: ['silver', 'blue'],
            colorTags: ['silver', 'blue'],
            colorCombination: 'silver & blue',
            description: 'Julius embellished Ankara on satin base.',
            size: '6 yards',
            sku: 'ANK-JES-024',
            pattern: 'Embellished'
        },
        {
            id: 'ANK025',
            name: 'Super-Wax Exclusive',
            price: 180000,
            image: 'images/ankara-exclusive.jpg',
            category: 'ankara',
            subcategory: 'Super Wax',
            colors: ['black', 'red', 'gold'],
            colorTags: ['black', 'red', 'gold'],
            colorCombination: 'black & red & gold',
            description: 'Exclusive super-wax Ankara collection.',
            size: '6 yards',
            sku: 'ANK-SWE-025',
            pattern: 'Exclusive'
        },
        {
            id: 'ANK026',
            name: 'Julius Crystal Shine',
            price: 100000,
            image: 'images/ankara-crystal.jpg',
            category: 'ankara',
            subcategory: 'Julius',
            colors: ['blue', 'silver'],
            colorTags: ['blue', 'silver'],
            colorCombination: 'blue & silver',
            description: 'Julius Ankara with crystal shine effect.',
            size: '6 yards',
            sku: 'ANK-JCS-026',
            pattern: 'Crystal'
        },
        {
            id: 'ANK027',
            name: 'Dutch Super-Wax Design 1',
            price: 297000,
            image: 'images/ankara-dutch.jpg',
            category: 'ankara',
            subcategory: 'Dutch Wax',
            colors: ['white', 'gold', 'blue'],
            colorTags: ['white', 'gold', 'blue'],
            colorCombination: 'white & gold & blue',
            description: 'Premium Dutch super-wax Ankara.',
            size: '6 yards',
            sku: 'ANK-DSW-027',
            pattern: 'Premium'
        },
        {
            id: 'ANK028',
            name: 'Guaranteed Dutch Super-Wax',
            price: 176000,
            image: 'images/ankara-guaranteed.jpg',
            category: 'ankara',
            subcategory: 'Dutch Wax',
            colors: ['gold', 'blue', 'black'],
            colorTags: ['gold', 'blue', 'black'],
            colorCombination: 'gold & blue & black',
            description: 'Guaranteed Dutch super-wax (6 yards).',
            size: '6 yards',
            sku: 'ANK-GDS-028',
            pattern: 'Premium'
        },
        {
            id: 'ANK029',
            name: 'Guaranteed Dutch Super-Wax (4 yards)',
            price: 117500,
            image: 'images/ankara-guaranteed-4yd.jpg',
            category: 'ankara',
            subcategory: 'Dutch Wax',
            colors: ['gold', 'black'],
            colorTags: ['gold', 'black'],
            colorCombination: 'gold & black',
            description: 'Guaranteed Dutch super-wax (4 yards).',
            size: '4 yards',
            sku: 'ANK-GD4-029',
            pattern: 'Premium'
        },
        {
            id: 'ANK030',
            name: 'Guaranteed Dutch Super-Wax Embellished',
            price: 226000,
            image: 'images/ankara-guaranteed-emb.jpg',
            category: 'ankara',
            subcategory: 'Dutch Wax',
            colors: ['gold', 'red', 'purple'],
            colorTags: ['gold', 'red', 'purple'],
            colorCombination: 'gold & red & purple',
            description: 'Embellished guaranteed Dutch super-wax.',
            size: '6 yards',
            sku: 'ANK-GDE-030',
            pattern: 'Embellished'
        }
    ],

    // Brocades Products (10 yards per piece)
    brocades: [
        {
            id: 'BRO001',
            name: 'Texil Magic Brocade Design 1',
            price: 100000,
            image: 'images/brocade-texil.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['gold', 'black'],
            colorTags: ['gold', 'black'],
            colorCombination: 'gold & black',
            description: 'Texil Magic brocade fabric.',
            size: '10 yards',
            sku: 'BRO-TXM-001',
            pattern: 'Royal'
        },
        {
            id: 'BRO002',
            name: 'Texil Magic Brocade Design 2',
            price: 100000,
            image: 'images/brocade-texil-2.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['silver', 'blue'],
            colorTags: ['silver', 'blue'],
            colorCombination: 'silver & blue',
            description: 'Texil Magic brocade with silver and blue patterns.',
            size: '10 yards',
            sku: 'BRO-TXM-002',
            pattern: 'Modern'
        },
        {
            id: 'BRO003',
            name: 'Texil Magic Brocade Design 3',
            price: 100000,
            image: 'images/brocade-texil-3.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['red', 'gold'],
            colorTags: ['red', 'gold'],
            colorCombination: 'red & gold',
            description: 'Texil Magic brocade with rich red and gold.',
            size: '10 yards',
            sku: 'BRO-TXM-003',
            pattern: 'Royal'
        },
        {
            id: 'BRO004',
            name: 'Texil Magic Brocade Design 4',
            price: 100000,
            image: 'images/brocade-texil-4.jpg',
            category: 'brocades',
            subcategory: 'Texil Magic',
            colors: ['purple', 'silver'],
            colorTags: ['purple', 'silver'],
            colorCombination: 'purple & silver',
            description: 'Elegant purple Texil Magic brocade.',
            size: '10 yards',
            sku: 'BRO-TXM-004',
            pattern: 'Elegant'
        },
        {
            id: 'BRO005',
            name: 'Victoria Elite Brocade',
            price: 250000,
            image: 'images/brocade-victoria-elite.jpg',
            category: 'brocades',
            subcategory: 'Victoria Elite',
            colors: ['purple', 'silver'],
            colorTags: ['purple', 'silver'],
            colorCombination: 'purple & silver',
            description: 'Premium Victoria Elite brocade.',
            size: '10 yards',
            sku: 'BRO-VEL-005',
            pattern: 'Elite'
        },
        {
            id: 'BRO006',
            name: 'Victoria Royal Brocade',
            price: 220000,
            image: 'images/brocade-victoria-royal.jpg',
            category: 'brocades',
            subcategory: 'Victoria Royal',
            colors: ['blue', 'gold'],
            colorTags: ['blue', 'gold'],
            colorCombination: 'blue & gold',
            description: 'Victoria Royal brocade fabric.',
            size: '10 yards',
            sku: 'BRO-VRO-006',
            pattern: 'Royal'
        },
        {
            id: 'BRO007',
            name: 'Getzener Magnum Brocade',
            price: 250000,
            image: 'images/brocade-getzener-magnum.jpg',
            category: 'brocades',
            subcategory: 'Getzener Magnum',
            colors: ['red', 'gold'],
            colorTags: ['red', 'gold'],
            colorCombination: 'red & gold',
            description: 'Getzener Magnum brocade.',
            size: '10 yards',
            sku: 'BRO-GTM-007',
            pattern: 'Magnum'
        },
        {
            id: 'BRO008',
            name: 'Getzener Texil Brocade',
            price: 100000,
            image: 'images/brocade-getzener-texil.jpg',
            category: 'brocades',
            subcategory: 'Getzener Texil',
            colors: ['black', 'silver'],
            colorTags: ['black', 'silver'],
            colorCombination: 'black & silver',
            description: 'Getzener Texil brocade fabric.',
            size: '10 yards',
            sku: 'BRO-GTX-008',
            pattern: 'Modern'
        },
        {
            id: 'BRO009',
            name: 'Getzener Gold (Ladies Brocade)',
            price: 150000,
            image: 'images/brocade-getzener-gold.jpg',
            category: 'brocades',
            subcategory: 'Getzener Gold',
            colors: ['gold', 'ivory'],
            colorTags: ['gold', 'ivory'],
            colorCombination: 'gold & ivory',
            description: 'Getzener Gold ladies brocade.',
            size: '10 yards',
            sku: 'BRO-GGL-009',
            pattern: 'Gold'
        }
    ],

    // Adires Products
    adires: [
        {
            id: 'ADI001',
            name: 'Glossy Adire Design 1',
            price: 5000,
            image: 'images/adire-glossy.jpg',
            category: 'adires',
            subcategory: 'Glossy',
            colors: ['blue', 'white'],
            colorTags: ['blue', 'white'],
            colorCombination: 'blue & white',
            description: 'Glossy finish Adire fabric.',
            size: '6 yards',
            sku: 'ADI-GLS-001',
            pattern: 'Traditional'
        },
        {
            id: 'ADI002',
            name: 'Glossy Adire Design 2',
            price: 5000,
            image: 'images/adire-glossy-2.jpg',
            category: 'adires',
            subcategory: 'Glossy',
            colors: ['indigo', 'white'],
            colorTags: ['indigo', 'white'],
            colorCombination: 'indigo & white',
            description: 'Deep indigo glossy Adire.',
            size: '6 yards',
            sku: 'ADI-GLS-002',
            pattern: 'Geometric'
        },
        {
            id: 'ADI003',
            name: 'Cotton Adire Design 1',
            price: 16000,
            image: 'images/adire-cotton.jpg',
            category: 'adires',
            subcategory: 'Cotton',
            colors: ['indigo', 'white'],
            colorTags: ['indigo', 'white'],
            colorCombination: 'indigo & white',
            description: 'Pure cotton Adire fabric.',
            size: '6 yards',
            sku: 'ADI-COT-003',
            pattern: 'Traditional'
        },
        {
            id: 'ADI004',
            name: 'Cotton Adire Design 2',
            price: 16000,
            image: 'images/adire-cotton-2.jpg',
            category: 'adires',
            subcategory: 'Cotton',
            colors: ['blue', 'brown'],
            colorTags: ['blue', 'brown'],
            colorCombination: 'blue & brown',
            description: 'Cotton Adire with blue and brown patterns.',
            size: '6 yards',
            sku: 'ADI-COT-004',
            pattern: 'Ethnic'
        },
        {
            id: 'ADI005',
            name: 'Adire Wax Design 1',
            price: 16000,
            image: 'images/adire-wax.jpg',
            category: 'adires',
            subcategory: 'Wax',
            colors: ['blue', 'yellow'],
            colorTags: ['blue', 'yellow'],
            colorCombination: 'blue & yellow',
            description: 'Adire with wax print patterns.',
            size: '6 yards',
            sku: 'ADI-WAX-005',
            pattern: 'Modern'
        },
        {
            id: 'ADI006',
            name: 'Adire Wax Design 2',
            price: 16000,
            image: 'images/adire-wax-2.jpg',
            category: 'adires',
            subcategory: 'Wax',
            colors: ['green', 'white', 'black'],
            colorTags: ['green', 'white', 'black'],
            colorCombination: 'green & white & black',
            description: 'Wax Adire with bold patterns.',
            size: '6 yards',
            sku: 'ADI-WAX-006',
            pattern: 'Abstract'
        }
    ],

    // Undivided Categories - Sample Products
    laces: [
        {
            id: 'LAC001',
            name: 'French Lace Design 1',
            price: 35000,
            image: 'images/lace-french.jpg',
            category: 'laces',
            subcategory: 'French',
            colors: ['white', 'ivory'],
            colorTags: ['white', 'ivory'],
            colorCombination: 'white & ivory',
            description: 'Premium French lace fabric.',
            size: '3 yards',
            sku: 'LAC-FRE-001',
            pattern: 'Floral'
        },
        {
            id: 'LAC002',
            name: 'French Lace Design 2',
            price: 35000,
            image: 'images/lace-french-2.jpg',
            category: 'laces',
            subcategory: 'French',
            colors: ['ivory'],
            colorTags: ['ivory'],
            colorCombination: 'ivory',
            description: 'Elegant ivory French lace.',
            size: '3 yards',
            sku: 'LAC-FRE-002',
            pattern: 'Delicate'
        },
        {
            id: 'LAC003',
            name: 'Swiss Lace Design 1',
            price: 42000,
            image: 'images/lace-swiss.jpg',
            category: 'laces',
            subcategory: 'Swiss',
            colors: ['white'],
            colorTags: ['white'],
            colorCombination: 'white',
            description: 'High-quality Swiss lace.',
            size: '3 yards',
            sku: 'LAC-SWI-003',
            pattern: 'Intricate'
        },
        {
            id: 'LAC004',
            name: 'Swiss Lace Design 2',
            price: 42000,
            image: 'images/lace-swiss-2.jpg',
            category: 'laces',
            subcategory: 'Swiss',
            colors: ['ivory'],
            colorTags: ['ivory'],
            colorCombination: 'ivory',
            description: 'Premium Swiss lace with intricate design.',
            size: '3 yards',
            sku: 'LAC-SWI-004',
            pattern: 'Premium'
        }
    ],

    asooke: [
        {
            id: 'ASO001',
            name: 'Traditional Aso-oke Design 1',
            price: 45000,
            image: 'images/asooke-traditional.jpg',
            category: 'asooke',
            subcategory: 'Traditional',
            colors: ['brown', 'gold'],
            colorTags: ['brown', 'gold'],
            colorCombination: 'brown & gold',
            description: 'Traditional handwoven Aso-oke.',
            size: '5 yards',
            sku: 'ASO-TRD-001',
            pattern: 'Traditional'
        },
        {
            id: 'ASO002',
            name: 'Traditional Aso-oke Design 2',
            price: 45000,
            image: 'images/asooke-traditional-2.jpg',
            category: 'asooke',
            subcategory: 'Traditional',
            colors: ['red', 'gold', 'green'],
            colorTags: ['red', 'gold', 'green'],
            colorCombination: 'red & gold & green',
            description: 'Vibrant traditional Aso-oke.',
            size: '5 yards',
            sku: 'ASO-TRD-002',
            pattern: 'Ethnic'
        },
        {
            id: 'ASO003',
            name: 'Modern Aso-oke Design 1',
            price: 38000,
            image: 'images/asooke-modern.jpg',
            category: 'asooke',
            subcategory: 'Modern',
            colors: ['black', 'silver'],
            colorTags: ['black', 'silver'],
            colorCombination: 'black & silver',
            description: 'Modern design Aso-oke.',
            size: '5 yards',
            sku: 'ASO-MOD-003',
            pattern: 'Modern'
        },
        {
            id: 'ASO004',
            name: 'Modern Aso-oke Design 2',
            price: 38000,
            image: 'images/asooke-modern-2.jpg',
            category: 'asooke',
            subcategory: 'Modern',
            colors: ['blue', 'silver', 'white'],
            colorTags: ['blue', 'silver', 'white'],
            colorCombination: 'blue & silver & white',
            description: 'Contemporary Aso-oke design.',
            size: '5 yards',
            sku: 'ASO-MOD-004',
            pattern: 'Contemporary'
        }
    ],

    // Featured Products for Homepage
    featured: [
        {
            id: 'ANK001',
            name: 'Hitarget Ankara',
            price: 15000,
            image: 'images/ankara-hitarget.jpg',
            category: 'ankara'
        },
        {
            id: 'BRO001',
            name: 'Texil Magic Brocade',
            price: 100000,
            image: 'images/brocade-texil.jpg',
            category: 'brocades'
        },
        {
            id: 'ADI001',
            name: 'Glossy Adire',
            price: 5000,
            image: 'images/adire-glossy.jpg',
            category: 'adires'
        },
        {
            id: 'LAC001',
            name: 'French Lace',
            price: 35000,
            image: 'images/lace-french.jpg',
            category: 'laces'
        }
    ]
};

// Helper function to get all products
function getAllProducts() {
    let allProducts = [];
    for (const category in productsData) {
        if (category !== 'featured') {
            allProducts = allProducts.concat(productsData[category]);
        }
    }
    return allProducts;
}

// Helper function to format price
function formatPrice(price) {
    return `₦${price.toLocaleString('en-NG')}`;
}
